name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['21','22']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven Wrapper
        run: ./mvnw clean test
